# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'LibTorchWrapper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VoizeLibTorch-Lite', '2.1.0'
end
