name: Publish package to Maven Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cocoapods-generate
        run: gem install cocoapods-generate
      - name: Publish package
        run: ./gradlew publish
        env:
          GITLAB_REGISTRY_URL: ${{ secrets.GITLAB_REGISTRY_URL }}
          GITLAB_REGISTRY_DEPLOY_TOKEN: ${{ secrets.GITLAB_REGISTRY_DEPLOY_TOKEN }}